import { readFileSync } from "fs";
import path from "path";

/**
 * Pre-baked feTurbulence grain tiles (generated by scripts/generate-grain-tiles.ts
 * using the JSON-spec baseFrequency / numOctaves settings). Loaded synchronously
 * and cached in memory on first access so Satori JSX can inline them directly.
 */
let cached: { coarse: string; fine: string } | null = null;

export function getGrainTiles() {
  if (cached) return cached;
  const dir = path.join(process.cwd(), "public", "grain");
  const coarse = readFileSync(path.join(dir, "grain-coarse.png")).toString("base64");
  const fine = readFileSync(path.join(dir, "grain-fine.png")).toString("base64");
  cached = { coarse, fine };
  return cached;
}
