import type { CoverSlideProps, ContentSlideProps, CtaSlideProps } from "../types";
import { getGrainTiles } from "../grain";

/**
 * Tayyib personal template — literal implementation of the user-supplied JSON
 * specs for cover / content / cta. No extras (no byline, no swipe arrow, no
 * page counter) — if they aren't in the JSON, they aren't rendered.
 *
 * Shared brand tokens are defined once and reused across all three slides.
 */

const W = 1080;
const H = 1350;

const COLORS = {
  background_primary: "#000000",
  accent_blue: "#3B82F6",
  accent_blue_deep: "#2563EB",
  accent_blue_darkest: "#1E3A8A",
  text_primary: "#FFFFFF",
  text_secondary: "rgba(255,255,255,0.7)",
} as const;

const SANS = "Outfit";              // stands in for "SF Pro Display, -apple-system, Helvetica Neue, system-ui"
const SERIF = "DM Serif Display";   // loaded at 400 italic (wedge-serif didone)

const SLIDE_PADDING = Math.round(W * 0.08);          // slide_horizontal_padding: "8%"
const CONTENT_PADDING = Math.round(W * 0.1);         // content_slide_padding: "10%"

// ─── Shared background layers ────────────────────────────────────────────

/** Subtle handle at the bottom-left of every slide. */
function Byline() {
  return (
    <div
      style={{
        position: "absolute",
        bottom: 40,
        left: 56,
        display: "flex",
        alignItems: "center",
      }}
    >
      <span
        style={{
          fontFamily: SANS,
          fontWeight: 400,
          fontSize: 22,
          color: "rgba(255,255,255,0.45)",
          letterSpacing: "-0.01em",
        }}
      >
        by @tayyib_ai
      </span>
    </div>
  );
}

/**
 * Base + gradient glow + two pre-baked feTurbulence grain tiles per JSON spec.
 * The grain PNGs are generated by scripts/generate-grain-tiles.ts and cached
 * at runtime by getGrainTiles().
 */
function BackgroundLayers() {
  const { coarse, fine } = getGrainTiles();
  return (
    <>
      {/* base */}
      <div style={{ position: "absolute", top: 0, left: 0, width: W, height: H, background: COLORS.background_primary }} />
      {/* gradient_glow — ellipse 110% 90% at 105% -5% (off-canvas top-right) */}
      <div
        style={{
          position: "absolute",
          top: 0,
          left: 0,
          width: W,
          height: H,
          background:
            "radial-gradient(ellipse 150% 120% at 105% -10%, #3B82F6 0%, #2458E0 14%, #1C3FBC 26%, #152A8F 40%, #0C1957 55%, rgba(6,10,40,0.7) 70%, transparent 92%)",
        }}
      />
      {/* bottom-left vignette for depth — deepens the shadow side so the blue feels richer by contrast */}
      <div
        style={{
          position: "absolute",
          top: 0,
          left: 0,
          width: W,
          height: H,
          background:
            "radial-gradient(ellipse 90% 80% at 10% 110%, rgba(0,0,0,0.85) 0%, rgba(0,0,0,0.6) 30%, rgba(0,0,0,0.25) 55%, transparent 80%)",
        }}
      />
      {/* grain_coarse — subtle, preserves the colour depth */}
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src={`data:image/png;base64,${coarse}`}
        alt=""
        width={W}
        height={H}
        style={{ position: "absolute", top: 0, left: 0, width: W, height: H, opacity: 0.08 }}
      />
      {/* grain_fine — very subtle */}
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src={`data:image/png;base64,${fine}`}
        alt=""
        width={W}
        height={H}
        style={{ position: "absolute", top: 0, left: 0, width: W, height: H, opacity: 0.04 }}
      />
    </>
  );
}

// ─── COVER ───────────────────────────────────────────────────────────────

export function TayyibCover({ headline, accentWord, subtitle, backgroundImage: _bg }: CoverSlideProps) {
  void _bg;
  // Map app data → JSON element IDs:
  //   title_line  = headline + optional subtitle (joined with the JSON's "\n")
  //   keyword_line = accentWord (rendered Playfair italic blue)
  const titleLine = [headline, subtitle].filter(Boolean).join("\n") || headline || "";
  const keywordLine = accentWord || "";

  return (
    <div style={{ width: W, height: H, display: "flex", position: "relative", overflow: "hidden" }}>
      <BackgroundLayers />

      <div
        style={{
          position: "absolute",
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          padding: `0 ${SLIDE_PADDING}px`,
        }}
      >
        {/* title_line — sized to match the other slides' headline weight (~88) */}
        {titleLine && (
          <span
            style={{
              fontFamily: SANS,
              fontWeight: 500,
              fontSize: 88,
              color: COLORS.text_primary,
              letterSpacing: "-0.02em",
              lineHeight: 1.05,
              textAlign: "center",
              whiteSpace: "pre-line",
            }}
          >
            {titleLine}
          </span>
        )}

        {/* keyword_line — DM Serif Display Italic at 80px (display face reads bold at 400) */}
        {keywordLine && (
          <span
            style={{
              fontFamily: SERIF,
              fontWeight: 400,
              fontStyle: "italic",
              fontSize: 80,
              color: COLORS.accent_blue,
              letterSpacing: "-0.01em",
              lineHeight: 1.05,
              marginTop: 16,
              textAlign: "center",
            }}
          >
            {keywordLine}
          </span>
        )}

        {/* hand_drawn_underline — scaled proportionally to the new keyword size */}
        {keywordLine && (
          <div style={{ marginTop: 12, display: "flex" }}>
            <svg width={680} height={134} viewBox="0 0 405 80">
              <path
                d="M 10 22 Q 200 14, 395 32"
                stroke={COLORS.accent_blue}
                strokeWidth={11}
                strokeLinecap="round"
                fill="none"
              />
              <path
                d="M 80 62 Q 250 42, 395 34"
                stroke={COLORS.accent_blue}
                strokeWidth={11}
                strokeLinecap="round"
                fill="none"
              />
              <circle cx={80} cy={62} r={8} fill={COLORS.accent_blue} />
            </svg>
          </div>
        )}
      </div>
      <Byline />
    </div>
  );
}

// ─── CONTENT (middle slides) ─────────────────────────────────────────────

export function TayyibContent({ headline, bodyText, backgroundImage: _bg }: ContentSlideProps) {
  void _bg;

  return (
    <div style={{ width: W, height: H, display: "flex", position: "relative", overflow: "hidden" }}>
      <BackgroundLayers />

      <div
        style={{
          position: "absolute",
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
          display: "flex",
          flexDirection: "column",
          alignItems: "flex-start",
          justifyContent: "center",
          padding: `${CONTENT_PADDING}px ${CONTENT_PADDING}px`, // "10% 10%"
        }}
      >
        {/* headline — 2× JSON: 80px (was 40), margin-bottom 40 (was 20) */}
        {headline && (
          <span
            style={{
              fontFamily: SANS,
              fontWeight: 500,
              fontSize: 80,
              color: COLORS.text_primary,
              letterSpacing: "-0.02em",
              lineHeight: 1.1,
              marginBottom: 40,
            }}
          >
            {headline}
          </span>
        )}

        {/* body_text — 2× JSON: 34px (was 17) */}
        {bodyText && (
          <span
            style={{
              fontFamily: SANS,
              fontWeight: 400,
              fontSize: 34,
              color: COLORS.text_secondary,
              lineHeight: 1.5,
            }}
          >
            {bodyText}
          </span>
        )}
      </div>
      <Byline />
    </div>
  );
}

// ─── CTA (final slide) ───────────────────────────────────────────────────

export function TayyibCta({ headline, ctaText, backgroundImage: _bg }: CtaSlideProps) {
  void _bg;
  const headlineText = headline || "";
  const rawCta = ctaText || "";

  // Pull a single-quoted UPPERCASE keyword out for the highlight + underline,
  // e.g. "Comment 'VIDEO' and I'll DM you the full breakdown"
  const match = rawCta.match(/^(.*?)(['"][A-Z0-9_ ]+['"])(.*)$/);
  const prefix = (match ? match[1] : rawCta).trimEnd();
  const keyword = match ? match[2] : null;
  const suffix = match ? match[3].trimStart() : "";

  return (
    <div style={{ width: W, height: H, display: "flex", position: "relative", overflow: "hidden" }}>
      <BackgroundLayers />

      <div
        style={{
          position: "absolute",
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          padding: `0 ${SLIDE_PADDING}px`,
        }}
      >
        {/* headline — 2× JSON: 88px (was 44), margin-bottom 64 (was 32) */}
        {headlineText && (
          <span
            style={{
              fontFamily: SANS,
              fontWeight: 500,
              fontSize: 88,
              color: COLORS.text_primary,
              letterSpacing: "-0.02em",
              lineHeight: 1.1,
              textAlign: "center",
              whiteSpace: "pre-line",
              marginBottom: 64,
            }}
          >
            {headlineText}
          </span>
        )}

        {/* cta_body — 2× JSON: 44px (was 22), underline scaled to 490 wide (was 245) */}
        {rawCta && (
          keyword ? (
            <div
              style={{
                display: "flex",
                flexDirection: "column",
                alignItems: "center",
                fontFamily: SANS,
                fontWeight: 500,
                fontSize: 44,
                color: COLORS.text_primary,
                letterSpacing: "-0.01em",
                lineHeight: 1.6,
                textAlign: "center",
              }}
            >
              {prefix && <span>{prefix}</span>}
              <span style={{ color: COLORS.accent_blue, lineHeight: 1.6 }}>{keyword}</span>
              <svg width={490} height={40} viewBox="0 0 245 20" style={{ display: "block" }}>
                <path
                  d="M 10 10 Q 120 2, 235 12"
                  stroke={COLORS.accent_blue}
                  strokeWidth={5}
                  strokeLinecap="round"
                  fill="none"
                />
              </svg>
              {suffix && <span>{suffix}</span>}
            </div>
          ) : (
            <span
              style={{
                fontFamily: SANS,
                fontWeight: 500,
                fontSize: 44,
                color: COLORS.text_primary,
                letterSpacing: "-0.01em",
                lineHeight: 1.6,
                textAlign: "center",
              }}
            >
              {rawCta}
            </span>
          )
        )}
      </div>
      <Byline />
    </div>
  );
}
